[package]
name = "hfps"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.148"
toml = "0.8"
glob = "0.3"

